name: Daily Scrum auto writting
run-name: ${{ github.actor }} is auto-writting his Daily scrum

on: 
  push: 
    branches: ['features-*']

permissions:
  issues: write
  contents: read

jobs: 
  auto-write-daily:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: debugging
        run: | 
          ls -la

      - name: Buscar el issue del daily scrum
        id: search
        run: |
          TODAY=$(date +'%Y-%m-%d')
          echo "Buscando Daily Scrum para la fecha: $TODAY"

          ISSUE_NUM=$(gh issue list --search "Daily Scrum in:title created:$TODAY" --label "SCRUM" --state open --json number --jq '.[0].number')
          echo "El numero de issue del daily scrum es: $ISSUE_NUM"
          echo "ISSUE_NUMBER=$ISSUE_NUM" >> $GITHUB_ENV
          
      - name: Escribir el daily scrum
        if: env.ISSUE_NUMBER != '' && env.ISSUE_NUMBER != 'null'
        run: |
          run: |
          # 1. USAMOS 'jq' PARA PARSEAR EL JSON DE EVENTOS
          # Leemos el archivo ${{ github.event_path }} para obtener los commits.
          # Usamos un filtro de jq para formatear cada commit como Markdown: '- [SHAcorto](URL) - Mensaje'
          # Guardamos el resultado en un archivo temporal llamado commit_log.md
          jq -r '.commits[] | "- [\(.sha | .[0:7])](\(.url)) - \(.message)"' ${{ github.event_path }} > commit_log.md
          
          cat << 'EOF' > comment.md
          *Daily generado por workflow*
          
          ## 👤 Participante: @${{ github.actor }}

          ### ✅ ¿Qué logré ayer?
          - 
          ### 🎯 ¿Qué voy a hacer hoy?
          - 
          ### 🎯 ¿Qué logre hacer hoy?
          - 
          EOF

          cat commit_log.md >> comment.md

          cat << 'EOF' >> comment.md
          ### 🛑 ¿Tengo algún impedimento?
          - [ ] No
          - [ ] Sí (Describir: )
          EOF

          gh issue comment ${{ env.ISSUE_NUMBER }} --body-file comment.md

          
