name: Continuous-Deployment
run-name: ${{ github.actor }} is executing the CD workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (backend)
        run: mvn clean package
        working-directory: backend/

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: fashtoll-jar
          path: backend/target/*.jar
